version: "3"
services:
  elk:
    build: ./ELK
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      -LS_HEAP_SIZE: "512m"
      -LS_OPTS: "--config.reload.automatic --config.reload.interval 5"
    volumes:
     - ./ELK/logstash/logStash.conf:/etc/logstash/conf.d/01.config.conf
     - ./ELK/scraper.py:/home/scraper.py
    